[workspace]

members = ["allem", "allem-derive"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"
repository = "https://github.com/TheNeikos/allem"
