[package]
name = "allem"
version = "0.1.0"
edition = "2021"

[dependencies]
allem-derive = { version = "0.1.0", path = "../allem-derive" }
itertools = "0.12.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
