[package]
name = "alles"
version = "0.1.0"
edition = "2021"

[dependencies]
alles-derive = { version = "0.1.0", path = "../alles-derive" }
itertools = "0.12.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
